### ISSUE TITLE
Requires mouse movement to draw (hard to draw dots)

### ISSUE THREAD

**Issue by oliver-cool-beans** [iamskab/Painter#10]
You must move the mouse in a direction to begin drawing a line. 
This makes it difficult to draw dots, as it requires mouse movement to draw. 
Would be better if we could start drawing on mouse down, instead of with movement.

**Comment by oliver-cool-beans** [comment]
Submitted my pull request to fix this one

**Comment by iamskab** [comment]
Hey @olivertribe I'll look over your 2 PRs .
Currently busy over my exam and other stuff .
Please try to add more issues if you can !
