### ISSUE TITLE
Add cap size demo when using shortcut "[ ]"

### ISSUE THREAD

**Issue by oliver-cool-beans** [iamskab/Painter#21]
Add a cap size demo when adjusting the cap size using the shortcuts "[ or ]" similar to the one used when increasing using the slider. 

when adjusting the cap size from the slider, a cap size demo appears in the top left, to show the user the size, without committing any strokes.
![image](https://user-images.githubusercontent.com/29847637/103432951-6e776800-4c3c-11eb-9122-576459b6cd9b.png)

when using the shortcut "[ or ]" to increase the cap size, the user has no idea how much they are increasing the cap size, until committing a stoke. It would be logical to add similar functionality as the slider, when using the shortcut.

**Comment by RishikeshSreekumar** [comment]
I have found the solution to this. Can you please assign me this task. @olivertribe @iamskab
